### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdd in position 1541: invalid continuation byte

### ISSUE THREAD

**Issue by ayhanbaris** [skavngr/rapidscan#39]
Traceback (most recent call last):
  File "/Users/ayhan/Downloads/rapidscan-master/rapidscan.py", line 1514, in <module>
    rs_tool_output_file = open(temp_file).read()
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdd in position 1541: invalid continuation byte

**Comment by ayhanbaris** [comment]
macos bigsur 11.6.2 , brew

**Comment by tristanlatr** [comment]
This might be related to the fact that rapidscan does not cleanup temps files correctly, see #32. Could you try with the proposed patch see if it solves your issue ?
